FROM node:17-alpine as builder

ENV NODE_ENV=dev
WORKDIR /app

COPY ./package.json ./yarn.lock /app/

RUN yarn install

COPY . /app/

RUN yarn run build

FROM node:17-alpine as production

ENV NODE_ENV=prod
WORKDIR /app

COPY ./package.json ./yarn.lock /app/

RUN apk update && apk add bash
RUN yarn install --production

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/.env /app/
CMD ["node", "dist/main"]