version: '3.7'
services:
  db:
    container_name: better-living-db
    hostname: dev|better-living-db
    image: postgres:14-alpine
    restart: always
    logging:
      driver: none
    environment: 
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nestjs:
    container_name: better-living-api
    hostname: dev|better-living-api
    image: better-living-api
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_PORT=${APP_PORT}
    command: yarn run start:dev
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: better-living-pgadmin4
    logging:
      driver: none
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports: 
      - 8080:80
    volumes: 
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgdata:
  pgadmin-data: