FROM node:16.13-alpine3.15 as builder

ENV NODE_ENV=dev
WORKDIR /app

COPY ./package.json /app/

RUN yarn install

COPY . /app/

RUN yarn run build

FROM node:16.13-alpine3.15 as production

ENV NODE_ENV=prod
WORKDIR /app

COPY ./package.json ./yarn.lock /app/

RUN apk update && apk add bash
RUN yarn install --production

COPY --from=builder /app/dist /app/dist
CMD ["node", "dist/main"]